/**
 * PDOC fixtures: cases generated by hand in the CRA's Payroll Deductions
 * Online Calculator. A fixture with any expected value still null is reported
 * as a todo. Once filled in, it must match PDOC to the cent: no tolerance.
 * See README "Adding a PDOC fixture".
 */
import { readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { dollarsToCents } from '../src/engine/money.ts'
import { editionForPayDate } from '../src/engine/params/select.ts'
import { computePeriod } from '../src/engine/withholding/periodic.ts'
import { PERIODS_PER_YEAR, type PayFrequency } from '../src/engine/withholding/types.ts'

interface PdocFixture {
  id: string
  description: string
  input: {
    payDate: string
    frequency: PayFrequency
    gross: string
    federalClaim: string
    ontarioClaim: string
    exempt: boolean
    ytd: { pensionable: string; cpp: string; cpp2: string; ei: string }
  }
  expected: Record<'cpp' | 'cpp2' | 'ei' | 'federalTax' | 'ontarioTax', string | null>
}

const DIR = join(import.meta.dirname, 'fixtures', 'pdoc')
const fixtures: PdocFixture[] = readdirSync(DIR)
  .filter((f) => f.endsWith('.json'))
  .sort()
  .map((f) => JSON.parse(readFileSync(join(DIR, f), 'utf8')) as PdocFixture)

describe('PDOC fixtures (exact to the cent)', () => {
  it('has the six seeded cases', () => {
    expect(fixtures.length).toBeGreaterThanOrEqual(6)
  })

  for (const fx of fixtures) {
    const filled = Object.values(fx.expected).every((v) => v !== null && v !== '')
    if (!filled) {
      it.todo(`${fx.id}: fill "expected" from PDOC (${fx.description})`)
      continue
    }
    it(`${fx.id}: ${fx.description}`, () => {
      const i = fx.input
      const r = computePeriod(editionForPayDate(i.payDate), {
        gross: dollarsToCents(i.gross),
        periodsPerYear: PERIODS_PER_YEAR[i.frequency],
        td1: {
          federalClaim: dollarsToCents(i.federalClaim),
          ontarioClaim: dollarsToCents(i.ontarioClaim),
          exempt: i.exempt,
        },
        ytd: {
          pensionable: dollarsToCents(i.ytd.pensionable),
          cpp: dollarsToCents(i.ytd.cpp),
          cpp2: dollarsToCents(i.ytd.cpp2),
          ei: dollarsToCents(i.ytd.ei),
        },
      })
      const e = fx.expected as Record<keyof PdocFixture['expected'], string>
      expect({
        cpp: r.cpp,
        cpp2: r.cpp2,
        ei: r.ei,
        federalTax: r.federalTax,
        ontarioTax: r.ontarioTax,
      }).toEqual({
        cpp: dollarsToCents(e.cpp),
        cpp2: dollarsToCents(e.cpp2),
        ei: dollarsToCents(e.ei),
        federalTax: dollarsToCents(e.federalTax),
        ontarioTax: dollarsToCents(e.ontarioTax),
      })
    })
  }
})
